package gregtech.api.event;

import net.minecraftforge.fml.common.eventhandler.Event;

/**
 * Fired right before processing handlers for autogenerated recipes are run for items with MaterialInfo.
 */
public final class MaterialInfoEvent extends Event {}
