package gregtech.api.recipes.builders;

import gregtech.api.GTValues;
import net.minecraft.item.ItemStack;

import javax.annotation.Nonnull;
import java.util.Collection;

public interface IResearchRecipeBuilder {

    int DEFAULT_DURATION = 144000;
    int DEFAULT_EUT = GTValues.VA[GTValues.LV];

    @Nonnull
    Collection<ResearchRecipeEntry> getRecipeEntries();

    /**
     * An entry for an autogenerated research recipe for producing a data item containing research data.
     */
    class ResearchRecipeEntry {

        private final String researchId;
        private final ItemStack researchStack;
        private final ItemStack dataStack;
        private final int duration;
        private final int EUt;

        /**
         * @param researchId the id of the research to store
         * @param researchStack the stack to scan for research
         * @param dataStack the stack to contain the data
         * @param duration the duration of the recipe
         * @param EUt the EUt of the recipe
         */
        public ResearchRecipeEntry(@Nonnull String researchId, @Nonnull ItemStack researchStack, @Nonnull ItemStack dataStack, int duration, int EUt) {
            this.researchId = researchId;
            this.researchStack = researchStack;
            this.dataStack = dataStack;
            this.duration = duration;
            this.EUt = EUt;
        }

        @Nonnull
        public String getResearchId() {
            return this.researchId;
        }

        @Nonnull
        public ItemStack getResearchStack() {
            return researchStack;
        }

        @Nonnull
        public ItemStack getDataStack() {
            return dataStack;
        }

        public int getDuration() {
            return duration;
        }

        public int getEUt() {
            return EUt;
        }
    }
}
