package gregtech.loaders.recipe;

import gregtech.api.GTValues;
import gregtech.api.recipes.loader.IRecipeLoader;

import javax.annotation.Nonnull;

public enum GTRecipeLoaders implements IRecipeLoader {
    /**
     * Sulfuric Acid
     */
    SULFURIC_ACID,
    /**
     * Nitric Acid
     */
    NITRIC_ACID,
    /**
     * Phosphoric Acid
     */
    PHOSPHORIC_ACID,
    /**
     * Acetic Acid
     */
    ACETIC_ACID,
    /**
     * Recipes for Voltage Coils
     */
    VOLTAGE_COILS,
    /**
     * Lubricant production
     */
    LUBRICANT,
    /**
     * Biomass production
     */
    BIOMASS,
    /**
     * Tungsten ore to dust processing
     */
    TUNGSTEN_PROCESSING,
    /**
     * The oil distillation and cracking recipes
     */
    PETROCHEM,
    /**
     * Misc distillation like biomass, liquid air, wood tar
     */
    DISTILLATION,
    /**
     * Centrifuging food into methane
     */
    FOOD_TO_METHANE,
    /**
     * Seed and fish oil
     */
    BIO_OILS,
    /**
     * Mixing for alloys like nichrome
     */
    ALLOY_MIXING,
    /**
     * The majority of chemical reactor recipes
     */
    REACTORS,
    /**
     * Polyethylene production
     */
    POLYETHYLENE,
    /**
     * PVC production
     */
    PVC,
    /**
     * PTFE production
     */
    PTFE,
    /**
     * Epoxy production
     */
    EPXOY,
    /**
     * Styrene-Butadiene Rubber production
     */
    SBR,
    /**
     * Polybenzimidazole production
     */
    PBI,
    /**
     * Polycaprolactam production
     */
    POLYCAPROLACTAM,
    /**
     * Silicone Rubber production
     */
    SILICONE,
    /**
     * Polyphenylene Sulfide production
     */
    POLYPHENYLENE_SULFIDE,
    /**
     * Polyvinyl Butyral production
     */
    POLYVINYL_BUTYRAL,
    /**
     * Combined LCR recipes
     */
    LCR,
    /**
     * Growth Medium recipes
     */
    GROWTH_MEDIUM,
    /**
     * Uranium Refining recipes
     */
    URANIUM_REFINING,
    /**
     * Fuel recipes like diesel or nitrobenzene
     */
    FUELS,
    /**
     * Platinum Refining recipes
     */
    PLATINUM_REFINING,
    /**
     * Naquadah Refining recipes
     */
    NAQUADAH_REFINING,
    /**
     * Gas liquefaction recipes
     */
    GAS_LIQUEFACTION,
    /**
     * All autogenerated decomposition recipes
     */
    DECOMPOSITION,
    /**
     * All autogenerated recycling recipes for both machines and material items
     */
    RECYCLING,
    /**
     * All wood processing recipes like pyrolyse oven recipes or log cutting to planks
     */
    WOOD_PROCESSING,
    /**
     * All material ingot processing
     */
    INGOT,
    /**
     * All material nugget processing
     */
    NUGGET,
    /**
     * All material block processing
     */
    BLOCK,
    /**
     * All material frame processing
     */
    FRAME,
    /**
     * All material dust processing
     */
    DUST,
    /**
     * All material dust compacting
     */
    DUST_COMPACTING,
    /**
     * All material gem conversion
     */
    GEM_CONVERSION,
    /**
     * All standard ore processing
     */
    ORE_PROCESSING,
    /**
     * All rod processing
     */
    STICK,
    /**
     * All long rod processing
     */
    STICK_LONG,
    /**
     * All plate processing
     */
    PLATE,
    /**
     * All double plate processing
     */
    PLATE_DOUBLE,
    /**
     * All dense plate processing
     */
    PLATE_DENSE,
    /**
     * All turbine blade processing
     */
    TURBINE_BlADE,
    /**
     * All rotor processing
     */
    ROTOR,
    /**
     * All bolt processing
     */
    BOLT,
    /**
     * All screw processing
     */
    SCREW,
    /**
     * All fine wire processing
     */
    WIRE_FINE,
    /**
     * All foil processing
     */
    FOIL,
    /**
     * All lens processing
     */
    LENS,
    /**
     * All large gear processing
     */
    GEAR,
    /**
     * All small gear processing
     */
    GEAR_SMALL,
    /**
     * All ring processing
     */
    RING,
    /**
     * All small spring processing
     */
    SPRING_SMALL,
    /**
     * All spring processing
     */
    SPRING,
    /**
     * All round processing
     */
    ROUND,
    /**
     * Fluid pipe recipes
     */
    FLUID_PIPE,
    /**
     * Item pipe recipes
     */
    ITEM_PIPE,
    /**
     * Restrictive pipe recipes
     */
    RESTRICTIVE_PIPE,
    /**
     * Polarizing recipes
     */
    POLARIZING,
    /**
     * Tool recipes
     */
    TOOLS,
    /**
     * Wire combining
     */
    WIRE_COMBINING,
    /**
     * Wire recipes
     */
    WIRES,
    /**
     * Assembly line recipes
     */
    ASSEMBLY_LINE,
    /**
     * Battery recipes
     */
    BATTERIES,
    /**
     * Circuit recipes
     */
    CIRCUITS,
    /**
     * LV-IV Motor recipes
     */
    MOTORS,
    /**
     * LuV-UV Motor recipes
     */
    MOTORS_HIGH,
    /**
     * LV-IV Piston recipes
     */
    PISTONS,
    /**
     * LuV-UV Piston recipes
     */
    PISTONS_HIGH,
    /**
     * LV-IV Robot arm recipes
     */
    ROBOT_ARMS,
    /**
     * LuV-UV Robot arm recipes
     */
    ROBOT_ARMS_HIGH,
    /**
     * LV-IV Conveyor recipes
     */
    CONVEYORS,
    /**
     * LuV-UV Conveyor recipes
     */
    CONVEYORS_HIGH,
    /**
     * LV-IV Pump recipes
     */
    PUMPS,
    /**
     * LuV-UV Pump recipes
     */
    PUMPS_HIGH,
    /**
     * Fluid regulator recipes
     */
    FLUID_REGULATORS,
    /**
     * LV-IV Sensor recipes
     */
    SENSORS,
    /**
     * LuV-UV Sensor recipes
     */
    SENSORS_HIGH,
    /**
     * LV-IV Emitter recipes
     */
    EMITTERS,
    /**
     * LuV-UV Emitter recipes
     */
    EMITTERS_HIGH,
    /**
     * LV-IV Field generator recipes
     */
    FIELD_GENERATORS,
    /**
     * LuV-UV Field generator recipes
     */
    FIELD_GENERATORS_HIGH,
    /**
     * Standard vanilla recipes
     */
    VANILLA,
    /**
     * Generator fuel recipes
     */
    POWER_GENERATION,
    /**
     * Fusion recipes
     */
    FUSION,
    /**
     * All hatch recipes
     */
    HATCHES,
    /**
     * All machine recipes and associated hulls
     */
    MACHINES,
    /**
     * All energy hatches, transformers, and related
     */
    POWER_DEVICES,
    /**
     * Fertilizer recipes
     */
    FERTILIZER;

    @Nonnull
    @Override
    public String getModid() {
        return GTValues.MODID;
    }
}
