name: Ask a Question
description: Ask a question regarding this project.
labels: [ "question" ]
body:
  - type: markdown
    attributes:
      value: |
        If you are in need of quick response, Discord may be a better place. We have quite an active Discord community, so you may get responses quicker. You can find a link to join in our README.md for this project.
        
        If you are looking for a gameplay wiki, we currently do not have one, however most information is available in-game info through tooltips or JEI/HEI. You can also ask any question on Discord, and someone will most likely have a response.
        
        If you are looking for API documentation or CT documentation, there is a wiki on GitHub which holds some relevant information. In addition, feel free to ask on Discord, we have specific channels for CraftTweaker help or general development questions.
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Feel free to ask any question regarding this project here.
      placeholder: "Example: How can I...?"
    validations:
      required: true
  - type: markdown
    attributes:
      value: Thank you for taking the time to ask us a question.
