name: Build Setup
description: Setup for standard Java builds

inputs:
  update-cache:
    description: If cache should be updated
    required: false
    default: false

runs:
  using: 'composite'

  steps:
  - name: Set up JDK 17
    uses: actions/setup-java@v4
    with:
      distribution: zulu
      java-version: 17

  - name: Setup Gradle
    uses: gradle/gradle-build-action@v2
    with:
      cache-write-only: ${{ inputs.update-cache }}
      generate-job-summary: false
      gradle-home-cache-includes: |
        caches
        caches/retro_futura_gradle
        notifications
        jdks
        wrapper
