# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        shell: bash
        run: |
          /usr/bin/git clone https://github.com/Gregicality/GregTech.git ./
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short $GITHUB_SHA)"
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload libs
        uses: actions/upload-artifact@v2
        with:
          name: libs
          path: build/libs/*.jar
  format:
    name: check-fmt
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        shell: bash
        run: |
          /usr/bin/git clone https://github.com/Gregicality/GregTech.git ./
      - name: Declare variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short $GITHUB_SHA)"
      - name: Set up JDK8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grand execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Formatter
        run: ./gradlew editorconfigCheck
